# Generated by Django 6.0.6 on 2026-08-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='jobs.importjob'),
            preserve_default=False,
        ),
    ]
