# Generated by Django 6.0.6 on 2026-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_person_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='inserted_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
    ]
