# Generated by Django 6.0.6 on 2026-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrating',
            name='is_abusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
