# Generated by Django 6.0.6 on 2026-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelrating_is_abusive_hotelrating_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
