# Generated by Django 6.0.6 on 2026-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
