# Generated by Django 6.0.6 on 2026-06-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_taskhistory_taskmanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='user',
        ),
    ]
