# Generated by Django 6.0.6 on 2026-06-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_company_rename_timestamp_taskhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
