# Generated by Django 6.0.6 on 2026-06-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_person_options_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
