# Generated by Django 6.0.6 on 2026-06-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_company_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
