# Generated by Django 6.0.6 on 2026-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_department_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tag',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
