# Generated by Django 6.0.6 on 2026-07-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_email', models.EmailField(max_length=254)),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
